Implements YAML configuration files
Shivansh-007/piston-cli pull request #16
Opened 2021-02-17 20:50 UTC by SuperMaZingCoder

This is an exciting PR! I've implemented configuration files. Very generally, the code runs like this:
1. CLI checks if the `--config` flag is passed. If it is, the CLI validates that location and if it is valid it **moves to step 3**. If it isn't, it tells the user and loads the defaults specified in `constants.py`.
2. If no flag is passed, the CLI checks the OS-specific default location specified in `constants.py`. If it is found: **move to step 3**. If it isn't, it lets the user know and loads the defaults specified in `constants.py`
**Note that all configuration can be overridden via the corresponding flag, e.g. `--theme`**
3. It reads through the config, getting only the values that can be configured, it lets the user know when it gets them. If a value is received that can't be configured, it lets the user know and skips it.
4. Any values that aren't specified are loaded from the defaults specified in `constants.py`.
5. Finally, in `piston/__init__.py`, each flag is set to use the configured values, only skipping them if a flag is passed to override it.

At the moment, only `theme` is configurable, though due to the way I've implemented it, it should be extremely easy. Just specify a default in `constants.py` and that's it, literally, that's it. Then just pass `config["config_key"]` (`"config_key"` being the new configurable value) to any methods that need it.

Here is an example `config.yaml` (**they must use the YAML format**):
```
theme:
    monokai
```

Let me know what you think!

2021-02-17 21:39 UTC, SuperMaZingCoder commented
Hold off on reviewing this for a bit, though, as I'd like to implement a few more things:
- Ensuring that the type of the parsed config is correct
- Using a class instead of two functions across modules

2021-02-17 22:48 UTC, SuperMaZingCoder commented
Alright, it should be good for reviewing! I'm super happy with its current state.

2021-02-20 07:25 UTC, SuperMaZingCoder commented
This change adds the addition of a config validator. For users implementing a new config option, this means they now also need to make a validator for that type to ensure it is correctly used.

2021-02-21 01:12 UTC, Shivansh-007 requested changes

2021-02-21 01:12 UTC, Shivansh-007 commented on piston/configuration/config_loader.py
> +                self.console.print(f"[green]- Loaded {key}: {value}[/green]")
Currently it fails when the use adds `-` in front of the theme name like:
```yaml
theme:
        - dracula
```
But this is very common in `yaml` files, so we can add support for it by checking if it is a `list` and its length is exactly `1`

```suggestion
                if isinstance(value, list) and len(value) == 1:
                    self._config[key] = value[0]
                else:
                    self._config[key] = value

                self.console.print(f"[green]- Loaded {key}: {self._config[key]}[/green]")
```

2021-02-21 01:12 UTC, Shivansh-007 commented on piston/utilities/constants.py
> +    }
What about `.yml` files? Both of the two are the same. (`.yaml` and `.yml`)

2021-02-21 09:29 UTC, Shivansh-007 commented on piston/configuration/config_loader.py
> +                self.console.print(f"[green]- Loaded {key}: {value}[/green]")
Another possibility is:
If the `theme` config is a list, it would randomly select from it.

2021-03-13 14:48 UTC, SuperMaZingCoder commented
Sorry for the break, I'll be working on this today!

2021-03-13 15:32 UTC, SuperMaZingCoder commented on piston/__init__.py
> +                args.shell, config["theme"] if not args.theme else args.theme
Won't this just pass in a boolean?

2021-03-13 15:34 UTC, SuperMaZingCoder commented on piston/__init__.py
> +            config["theme"] if not args.theme else args.theme
Hmm, this seems to be already implemented.

2021-03-13 15:35 UTC, SuperMaZingCoder commented on piston/__init__.py
> +    config_loader = ConfigLoader(args.config if args.config else None)
I think that will only pass a boolean.

2021-03-13 15:37 UTC, SuperMaZingCoder commented on piston/configuration/config_loader.py
> +        self._path = path
Won't this just use a boolean?

2021-03-13 15:38 UTC, SuperMaZingCoder commented on piston/configuration/config_loader.py
> +                self.console.print(f"[green]- Loaded {key}: {value}[/green]")
I think we discussed this in Discord, I'll opt for the second route because I can just check if it is a list, and if it is, notify the user that it will be picked from randomly, even if it is only one theme, it will make more sense than just letting lists of length one act differently, I think.

2021-03-13 15:39 UTC, SuperMaZingCoder commented on piston/utilities/constants.py
> +    }
Sounds good, I'll just make it the key values into lists that stores all of the default locations for each os.

2021-03-13 15:53 UTC, Shivansh-007 commented on piston/__init__.py
> +                args.shell, config["theme"] if not args.theme else args.theme
Nope, the `or` operator returns the first True value or the last value if nothing is True. Note that if a True value is found, the values in the expressions after that value are not evaluated.

2021-03-13 15:54 UTC, Shivansh-007 commented on piston/configuration/config_loader.py
> +                self.console.print(f"[green]- Loaded {key}: {value}[/green]")
> I think we discussed this in Discord, I'll opt for the second route because I can just check if it is a list, and if it is, notify the user that it will be picked from randomly, even if it is only one theme, it will make more sense than just letting lists of length one act differently, I think.

Right, go ahead with the second route.

2021-03-16 02:06 UTC, Shivansh-007 requested changes
This is purely a code review, haven’t tested it as of now and it looks solid!

2021-03-16 02:23 UTC, SuperMaZingCoder commented on piston/utilities/constants.py
> -themes = [list(themes[style : style + 2]) for style in range(0, len(themes), 2)]
I'll check, I think I changed that a while back, though it likely had something to do with how configs are now done.

2021-03-16 02:23 UTC, SuperMaZingCoder commented on piston/utilities/constants.py
> -themes = [list(themes[style : style + 2]) for style in range(0, len(themes), 2)]
What does that code actually do by the way?

2021-03-16 04:26 UTC, Shivansh-007 commented on piston/utilities/constants.py
> -themes = [list(themes[style : style + 2]) for style in range(0, len(themes), 2)]
https://github.com/Shivansh-007/piston-cli/blob/094d30a0413cded095335558150863bc2953c4c9/piston/__init__.py#L25

2021-03-26 10:15 UTC, Shivansh-007 requested changes
Could you please revert the un required (the `media` and `README` changes) changes?

2021-03-26 10:15 UTC, Shivansh-007 commented on piston/configuration/choose_config.py
> +    if type(config) is list:
You can use `isinstance()` here,
```suggestion
    if isinstance(config, list):
```

2021-03-26 10:15 UTC, Shivansh-007 commented on piston/configuration/config_loader.py
> +        elif type(self.paths) is tuple:
```suggestion
        if isinstance(self.paths, str):
            if os.path.isfile(self.paths):
                path_exists = True
        elif isinstance(self.paths, tuple):
```

2021-03-26 10:15 UTC, Shivansh-007 commented on piston/configuration/validators/theme_validator.py
> +        if type(self.themes) is str and not ThemeValidator.check_theme_exists(
```suggestion
        if isinstance(self.themes, str) and not ThemeValidator.check_theme_exists(
```

2021-03-26 10:15 UTC, Shivansh-007 commented on piston/configuration/validators/theme_validator.py
> +        if type(self.themes) is list:  # Check each theme exists.
```suggestion
        if isinstance(self.themes, list):  # Check each theme exists.
```

2021-03-26 10:15 UTC, Shivansh-007 commented on piston/configuration/validators/validator_base.py
> +                if type(item) is not self.target_type:
```suggestion
                if not isinstance(item, self.target_type):
```

2021-03-26 10:15 UTC, Shivansh-007 commented on piston/configuration/config_loader.py
> +                "[blue]One or more configuration files was found to exist. "
```suggestion
                "[blue]One or more configuration files were found to exist. "
```
`was` doesn't agree with the subject.

2021-03-30 21:22 UTC, Shivansh-007 approved these changes
Thanks! Looks Good To Me! :shipit:

2021-04-08 13:18 UTC, merged