Added ArchOS installation info
Shivansh-007/piston-cli pull request #37
Opened 2021-03-11 18:31 UTC by KeneePatel

## Relevant Issues
Relevant to issue #3   

## Description
Just added info for installing in a arch based system.

## Reasoning
Made a PKGBUILD and then uploaded the same to AUR.

## Screenshots
![image](https://user-images.githubusercontent.com/59523692/110836186-c62df180-82c5-11eb-8549-baf0b37fa68c.png)

## Did you:

- [x] Join the [**Piston CLI Discord Community**](https://discord.gg/c7dZ4zdGQT)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

2021-03-12 01:49 UTC, ShotgunFlamez commented on README.md
> +```
??? This Is Stupid, And Ur A Foot

2021-03-12 01:51 UTC, Shivansh-007 approved these changes
Awesome! Looks Good to Me. I asked few of my friends to test it and it works great!

2021-03-12 01:54 UTC, Shivansh-007 commented
https://aur.archlinux.org/packages/piston-cli-git/ Can we change the maintainer to @SuperMaZingCoder and me here,  and if possible remove the last contributor?

2021-03-12 03:17 UTC, RohanJnr commented
`ModuleNotFoundError: No module named 'prompt_toolkit'` when I tried piston -h after installing using `yay`

2021-03-12 03:32 UTC, Shivansh-007 requested changes
Few comments on your PKGBUILD,
```bash
# Maintainer: Kenee Patel  <patelkenee2804 + aur at gmail <.> com>
pkgname=piston-cli-git
_pkgname=piston-cli
pkgver=r71.094d30a
pkgrel=1
pkgdesc="A universal shell supporting 36+ languages, in terminal code editor with syntax highlight, code compiler (36+ languages). It can run code from pastebin links and files too. "
arch=('any')
url="https://github.com/Shivansh-007/piston-cli.git"
license=('MIT')
depends=('python' 'python-pip' 'python-rich')
makedepends=('git')
optdepends=()
provides=('piston-cli')
conflicts=('piston-cli')
source=('git'+$url)
sha256sums=('SKIP')

build() {
	cd "$_pkgname"
	python setup.py build
}

package() {
	cd "$_pkgname"
	python setup.py install --root="${pkgdir}/" --optimize=1 --skip-build
	install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
}

pkgver() {
    cd "$srcdir/$_pkgname"
    printf "r%s.%s" $(git rev-list --count HEAD) $(git rev-parse --short HEAD)
}
```

1. Change the maintainer's name and email address to Supermazingcoder's.
2. Change the depends and make depends to:
	```bash
	depends=('python-pygments'
	'python-requests'
	'python-prompt_toolkit'
	'python-rich'
	'python-argparse')
	makedepends=('python-setuptools') 
	```
3. We would be shifting to use github releases so we would need support for that, so you can have a look at https://github.com/archlinux/svntogit-community/blob/packages/httpie/trunk/PKGBUILD (httpie's PKGBUILD). 
4. Add the PKGBUILD to `packaging/` or `scripts/` maybe.

2021-03-12 05:37 UTC, KeneePatel commented
Okay I was meaning to change it beforehand just putted mine in as temporary email only.

2021-03-12 06:53 UTC, Shivansh-007 commented on packaging/PKGBUILD
> +)
Indentation issues ^
```suggestion
depends=(
    "python-pygments"
    "python-requests"
    "python-prompt_toolkit"
    "python-rich"
    "python-argparse"
)

```

2021-04-14 11:36 UTC, Shivansh-007 approved these changes

2021-04-14 11:37 UTC, merged