Implemented shell flag
Shivansh-007/piston-cli pull request #9
Opened 2021-02-16 07:30 UTC by SuperMaZingCoder

# Overview
This flag allows launches a shell-like environment for running code via the Piston API. This is a WIP pr as of now, as it breaks the "flagless" piston-cli command from my testing. I also need to add newlines between the compilation and prompts for args and stdin as well as documenting that `esc + enter` is requred to send the code to the API. 

Other than that, the shell command is working perfectly!

# Screenshots
![image](https://user-images.githubusercontent.com/55718659/108031362-9997fa00-6fe5-11eb-9f79-4315fa331ab3.png)

2021-02-16 07:41 UTC, Shivansh-007 reviewed
Nicely done! But in the python REPL we can't really give it system arguments, so I don't we need to give it here. Secondly I think the stdin arguments should be asked after the code is give.
And last, the language should be specified while running the command that is:
```bash
$ piston --shell python
```

2021-02-16 14:27 UTC, SuperMaZingCoder commented
Thanks! I'm not sure about dropping system arguments to be better lined up with the python REPL; already, data is not stored between "REPL code runs" and I think that makes it a tool to repeatedly run the piston-cli. If that is the goal - to write all code once and test it out - I think that system arguments should be a provided option. If the distinction I made is a bit confusing or you still think we should drop system arguments, let me know!

As for putting stdin *after* the code prompt, I'm okay with this, though, I think we should change that in the "flagless" execution too if we do so.

2021-02-16 17:10 UTC, SuperMaZingCoder commented
After some more testing, it seems like it doesn't break the other flags, but flagless piston is strangely asking for the language twice.

2021-02-17 01:09 UTC, Shivansh-007 commented
> Thanks! I'm not sure about dropping system arguments to be better lined up with the python REPL; already, data is not stored between "REPL code runs" and I think that makes it a tool to repeatedly run the piston-cli. If that is the goal - to write all code once and test it out - I think that system arguments should be a provided option. If the distinction I made is a bit confusing or you still think we should drop system arguments, let me know!
> 
> As for putting stdin _after_ the code prompt, I'm okay with this, though, I think we should change that in the "flagless" execution too if we do so.

Ok agree with the first point, and yeah you can put the stdin after the code prompt and maybe even the sys arguments (not sure about this).

2021-02-17 01:17 UTC, Shivansh-007 requested changes

2021-02-17 01:17 UTC, Shivansh-007 commented on piston/commands/from_shell.py
> +            ">>> ",
This should be a constant.

2021-02-17 01:17 UTC, Shivansh-007 commented on piston/commands/from_shell.py
> +            self.console.print("[bold red]Language is not supported![/bold red]")
We are using the style argument as decided. (Am not putting this for all such cases but yeah it is meant for all).

2021-02-17 01:17 UTC, Shivansh-007 commented on piston/commands/from_shell.py
> +        self, code: str, args: List[str], style: Style, stdin: str
Parameter `style` is not used

2021-02-17 01:17 UTC, Shivansh-007 commented on piston/commands/from_shell.py
> +        while output != "exit":
We can have a list of "Exit" words like `quit`, `bye`, `cya`.

2021-02-17 01:17 UTC, Shivansh-007 commented on piston/commands/from_shell.py
> +            return "Your code ran without output.", self.language
Add this as a constant as it is being used multiple times. Not in this file but yeah in few others.

2021-02-17 01:17 UTC, Shivansh-007 commented on piston/commands/from_shell.py
> +    def query_piston(
We can make `query_piston` a utils function as it is being used in multiple files.

2021-02-17 01:17 UTC, Shivansh-007 commented on piston/commands/from_shell.py
> +        return stdin
We can make this a utils function.

2021-02-17 01:18 UTC, SuperMaZingCoder commented
> Ok agree with the first point, and yeah you can put the stdin after the code prompt and maybe even the sys arguments (not sure about this).

Alright. We should document that the stdin/args comes *after* the code in this case. I think if we do this, we need to change it for `from_input` too, and possibly the others.

2021-02-17 01:18 UTC, SuperMaZingCoder commented on piston/commands/from_shell.py
> +            ">>> ",
You mean the `">>> "`, right? I agree with that.

2021-02-17 01:19 UTC, SuperMaZingCoder commented on piston/commands/from_shell.py
> +            self.console.print("[bold red]Language is not supported![/bold red]")
👍 I'll change those, note that we'll have to do the same for the other execution methods in the future.

2021-02-17 01:19 UTC, SuperMaZingCoder commented on piston/commands/from_shell.py
> +        self, code: str, args: List[str], style: Style, stdin: str
👍

2021-02-17 01:20 UTC, SuperMaZingCoder commented on piston/commands/from_shell.py
> +        while output != "exit":
Sounds good, I'll add this to `constants.py`

2021-02-17 01:20 UTC, SuperMaZingCoder commented on piston/commands/from_shell.py
> +            return "Your code ran without output.", self.language
Which part?

2021-02-17 01:20 UTC, Shivansh-007 commented on piston/commands/from_shell.py
> +            ">>> ",
Yeah!

2021-02-17 01:21 UTC, Shivansh-007 commented on piston/commands/from_shell.py
> +            return "Your code ran without output.", self.language
`Your code ran without output.`

2021-02-17 01:21 UTC, SuperMaZingCoder commented on piston/commands/from_shell.py
> +            return "Your code ran without output.", self.language
I think we should save this for the time we format everything, and keep this PR just for shell execution.

2021-02-17 01:21 UTC, SuperMaZingCoder commented on piston/commands/from_shell.py
> +    def query_piston(
I think we should save this for the time we format everything, and keep this PR just for shell execution.

2021-02-17 01:22 UTC, SuperMaZingCoder commented on piston/commands/from_shell.py
> +        return stdin
I think we should save this for the time we format everything, and keep this PR just for shell execution.

2021-02-17 01:24 UTC, Shivansh-007 commented on piston/commands/from_shell.py
> +            return "Your code ran without output.", self.language
> I think we should save this for the time we format everything, and keep this PR just for shell execution.

Alright. No Problem.

2021-02-17 01:25 UTC, Shivansh-007 commented on piston/commands/from_shell.py
> +    def query_piston(
> I think we should save this for the time we format everything, and keep this PR just for shell execution.

Alright. No Problem.

2021-02-17 01:25 UTC, Shivansh-007 commented on piston/commands/from_shell.py
> +        return stdin
Alright. No Problem.

2021-02-17 01:29 UTC, SuperMaZingCoder commented on piston/commands/from_shell.py
> +            ">>> ",
Sounds good! :D

2021-02-17 04:25 UTC, SuperMaZingCoder commented
I've implemented what we discussed, though there is some strange behavior in that it does not display the compilation output until enter is clicked on the next prompt. Any ideas about what could be happening here?

2021-02-17 04:34 UTC, SuperMaZingCoder commented
So, turns out that this was just an issue with Visual Studio's terminal, this should be good to merge at this point! Of course, if there is anything that needs to be fixed, let me know :D

2021-02-17 05:36 UTC, Shivansh-007 approved these changes

2021-02-17 05:36 UTC, merged